### ISSUE TITLE
Invalid URL: undefined when "npm run compose" 

### ISSUE THREAD

**Issue by alexisgauba** [enKryptIO/ethvm-socket-server#6]
When I launch "npm run compose", I get the following: 

[nodemon] app crashed - waiting for file changes before starting...

Accompanied by this TypeError: 
TypeError [ERR_INVALID_URL]: Invalid URL: undefined
    at onParseError (internal/url.js:219:17)
    at parse (internal/url.js:228:3)
    at new URL (internal/url.js:311:5)
    at connectWithCert (/home/agauba/ethvm-socket-server/dist/index.js:3557:23)
    at RethinkDB.start (/home/agauba/ethvm-socket-server/dist/index.js:3575:13)
    at new RethinkDB (/home/agauba/ethvm-socket-server/dist/index.js:3535:14)
    at Object.defineProperty.value (/home/agauba/ethvm-socket-server/dist/index.js:3452:11)
    at __webpack_require__ (/home/agauba/ethvm-socket-server/dist/index.js:20:30)
    at /home/agauba/ethvm-socket-server/dist/index.js:63:18
    at Object.<anonymous> (/home/agauba/ethvm-socket-server/dist/index.js:66:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

Was having a lot of difficulty progressing past this issue to be able to run the socket-server. Am able to run the front end, but as a result of the above, am unable to access the data.

**Comment by kvhnuke** [comment]
@niktrix can you please check
