### ISSUE TITLE
npm start Error

### ISSUE THREAD

**Issue by StormSpirit22** [enKryptIO/ethvm-socket-server#8]
I've tried many times to checkout code and install, using latest code and npm start, report errors:
```
TypeError: Cannot read property 'each' of undefined
    at r.table.changes.map.merge.run (/Users/atmatrix/Documents/GitHub/explorer/ethvm-socket-server/dist/index.js:3685:19)
    at tryCatcher (/Users/atmatrix/Documents/GitHub/explorer/ethvm-socket-server/node_modules/rethinkdb/node_modules/bluebird/js/main/util.js:26:23)
    at Promise.errorAdapter (/Users/atmatrix/Documents/GitHub/explorer/ethvm-socket-server/node_modules/rethinkdb/node_modules/bluebird/js/main/nodeify.js:36:34)
    at Promise._settlePromiseAt (/Users/atmatrix/Documents/GitHub/explorer/ethvm-socket-server/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:582:21)
    at Promise._settlePromises (/Users/atmatrix/Documents/GitHub/explorer/ethvm-socket-server/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/Users/atmatrix/Documents/GitHub/explorer/ethvm-socket-server/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/atmatrix/Documents/GitHub/explorer/ethvm-socket-server/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/atmatrix/Documents/GitHub/explorer/ethvm-socket-server/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! ethvm-socket-server@0.0.1 start: `node dist/index.js --remoteRDB --rawCert`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the ethvm-socket-server@0.0.1 start script.
```
How do I solved this?

And I tried npm run build, also have errors:
```
ERROR in ./src/rethinkConn.ts
[tsl] ERROR in /Users/atmatrix/Documents/GitHub/explorer/ethvm-socket-server/src/rethinkConn.ts(229,20)
      TS2345: Argument of type 'RTime' is not assignable to parameter of type 'string | RValue<string> | ReturnsType<string | RValue<string>> | ((row: RObject<{}>) => RValue<{}...'.
  Type 'RTime' has no properties in common with type 'GroupOptions'.

ERROR in ./src/rethinkConn.ts
[tsl] ERROR in /Users/atmatrix/Documents/GitHub/explorer/ethvm-socket-server/src/rethinkConn.ts(279,20)
      TS2345: Argument of type 'RTime' is not assignable to parameter of type 'string | RValue<string> | ReturnsType<string | RValue<string>> | ((row: RObject<{}>) => RValue<{}...'.
  Type 'RTime' has no properties in common with type 'GroupOptions'.
```

Does anybody encountered all these errors?

**Comment by StormSpirit22** [comment]
Ps. npm run compose is same as npm start, I've also tried.

**Comment by kvhnuke** [comment]
Did you get a chance to read through https://github.com/enKryptIO/ethvm/blob/master/README.md ?

**Comment by StormSpirit22** [comment]
Of course I read, what do you wanna say?

**Comment by StormSpirit22** [comment]
I've start rethinkdb, redis in my local, and I've ser RPC_HOST to a private chain node. My front-end interface is working, but server is always these errors. I've tried docker-compose up, it says:
```
ERROR: pull access denied for enkryptio/ethvm-socket-server, repository does not exist or may require 'docker login'
```
But I logged in before, I can pull other images but this,  so I wanna try run server separately not in docker. You have some useful suggestions?

**Comment by niktrix** [comment]
@stotmspirit22 you need to setum ethvm geth, it wont work for default geth clieth

**Comment by niktrix** [comment]
@StormSpirit22 you need to create image using Dockerfile given

**Comment by StormSpirit22** [comment]
@niktrix ok thanks man, I just thought they are the same thing.

**Comment by StormSpirit22** [comment]
It works, thanks a lot ! @kvhnuke @niktrix
